# Generated by Django 3.2.9 on 2021-12-01 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('priority', models.CharField(choices=[('LO', 'Low'), ('MD', 'Medium'), ('HI', 'High')], max_length=2)),
                ('state', models.CharField(choices=[('RE', 'Resolved'), ('UN', 'Unresolved')], max_length=2)),
                ('project_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='projects_app.project')),
            ],
        ),
    ]
